### ISSUE TITLE
Creates a demo that shows agent being aware of rules

### ISSUE THREAD

**Issue by francocipollone** [maliput/delphyne_demos#38]
### Summary

At the moment we don't have any demo that exercise the ability of `maliput` of handling several states per rule, and the dynamism that 
this situation could add to an agent simulation.

As a reference, `maliput_integration` already provides an example of a dynamic environment: See [maliput_dynamic_environment](https://github.com/ToyotaResearchInstitute/maliput_integration/blob/main/tutorials/maliput_dynamic_environment_app.md) app.

#### Prerequisites for the demo

Delphyne must provide handling for changing rules and the agents should be aware of the rules.
 - [x] Provide System for handling dynamic environments https://github.com/ToyotaResearchInstitute/delphyne/issues/825 https://github.com/ToyotaResearchInstitute/delphyne/issues/827 
 - [x] Provide/Modify Agent for being aware of the rule's states when traversing the Road Network. https://github.com/ToyotaResearchInstitute/delphyne/issues/830
 - [x] Build traffic light meshes and add them to the scene. It should handle the variable bulb states. https://github.com/ToyotaResearchInstitute/delphyne/issues/834
 
 #### Demo
 
 - [x] Add a demo to delphyne_demos. It could be added withing `mali` demo. https://github.com/ToyotaResearchInstitute/delphyne_demos/pull/39
